In [1]:
import os, sys
ppp = os.getcwd()
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from IPython.display import Image, display
import numpy as np
import matplotlib.pyplot as plt
import math
from Pedro_package import Pedro_Variable, Pedro_Function
from Pedro_package.utils import get_dot_graph, plot_dot_graph
import Pedro_package.functions as F

ModuleNotFoundError: No module named 'Pedro_package'

In [2]:
x = Pedro_Variable(np.array([1, 2, 3, 4, 5, 6]))
y = F.sum(x)
y.backward()

print(y)
print(x.grad)

NameError: name 'Pedro_Variable' is not defined

In [3]:
x = Pedro_Variable(np.array([[1, 2, 3],
                             [4, 5, 6]]))
y = F.sum(x)
y.backward()

print(y)
print(x.grad)

NameError: name 'Pedro_Variable' is not defined

In [4]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y1 = np.sum(x, axis=0)
y2 = np.sum(x, axis=0, keepdims=True)
z1 = np.sum(x, axis=1)
z2 = np.sum(x, axis=1, keepdims=True)

print(y1)
print(x.shape, ' -> ', y1.shape)
print(y2)
print(x.shape, ' -> ', y2.shape)
print(z1)
print(x.shape, ' -> ', z1.shape)
print(z2)
print(x.shape, ' -> ', z2.shape)

[5 7 9]
(2, 3)  ->  (3,)
[[5 7 9]]
(2, 3)  ->  (1, 3)
[ 6 15]
(2, 3)  ->  (2,)
[[ 6]
 [15]]
(2, 3)  ->  (2, 1)


In [5]:
aa = Pedro_Variable(np.array([[1, 2, 3],
                              [4, 5, 6]]))
bb = F.sum(aa, axis=0)
bb.backward()

print(bb)
print(aa.grad)

aa = Pedro_Variable(np.random.randn(2, 3, 4, 5))
bb = aa.sum(keepdims=True)
print(bb.shape)

NameError: name 'Pedro_Variable' is not defined