In [1]:
import os, sys
ppp = os.getcwd()
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from IPython.display import Image, display
import numpy as np
import matplotlib.pyplot as plt
import math
from Pedro_package import Pedro_Variable, Pedro_Function
from Pedro_package.utils import get_dot_graph, plot_dot_graph
import Pedro_package.functions as F

ModuleNotFoundError: No module named 'Pedro_package'

In [2]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.reshape(x, (6, ))
z = x.reshape((6, ))
print(y)
print(z)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [3]:
aa = Pedro_Variable(np.array([[1, 2, 3],
                              [4, 5, 6]]))
bb = F.reshape(aa, (6, ))
bb.backward(retain_graph=True)

print(aa)
print(bb)
print(bb.grad)
print(aa.grad)

NameError: name 'Pedro_Variable' is not defined

In [4]:
x = np.random.rand(1, 2, 3)

y1 = x.reshape((2, 3))
y2 = x.reshape([2, 3])
y3 = x.reshape(2, 3)

print(y1)
print(y2)
print(y3)

[[0.31833177 0.64321383 0.26949521]
 [0.43635936 0.4125047  0.13287413]]
[[0.31833177 0.64321383 0.26949521]
 [0.43635936 0.4125047  0.13287413]]
[[0.31833177 0.64321383 0.26949521]
 [0.43635936 0.4125047  0.13287413]]


In [5]:
x = Pedro_Variable(np.random.randn(1, 2, 3))

y1 = x.reshape((2, 3))
y2 = x.reshape([2, 3])
y3 = x.reshape(2, 3)

print(y1)
print(y2)
print(y3)

NameError: name 'Pedro_Variable' is not defined

In [6]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = x.transpose()

print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [7]:
aa = Pedro_Variable(np.array([[1, 2, 3],
                              [4, 5, 6]]))
bb = F.transpose(aa)
bb.backward(retain_graph=True)

print(aa)
print(bb)
print(bb.grad)
print(aa.grad)

NameError: name 'Pedro_Variable' is not defined

In [8]:
aa = Pedro_Variable(np.array([[1, 2, 3],
                              [4, 5, 6]]))
bb = aa.transpose()
print(bb)
cc = aa.T
print(cc)

NameError: name 'Pedro_Variable' is not defined

In [9]:
A, B, C, D = 1, 2, 3, 4
x = np.random.rand(A, B, C, D)
y = x.transpose()
z = x.transpose(1, 0, 3, 2)

print(x)
print('=' * 50)
print(y)
print('=' * 50)
print(z)

[[[[0.2501103  0.87468871 0.94307772 0.53762147]
   [0.80609755 0.27541785 0.92782878 0.60430607]
   [0.32868076 0.9289837  0.36063559 0.74300285]]

  [[0.58815102 0.48053308 0.07572209 0.92797601]
   [0.98049858 0.27814212 0.56406903 0.98540781]
   [0.63130771 0.86343307 0.59012648 0.06124855]]]]
[[[[0.2501103 ]
   [0.58815102]]

  [[0.80609755]
   [0.98049858]]

  [[0.32868076]
   [0.63130771]]]


 [[[0.87468871]
   [0.48053308]]

  [[0.27541785]
   [0.27814212]]

  [[0.9289837 ]
   [0.86343307]]]


 [[[0.94307772]
   [0.07572209]]

  [[0.92782878]
   [0.56406903]]

  [[0.36063559]
   [0.59012648]]]


 [[[0.53762147]
   [0.92797601]]

  [[0.60430607]
   [0.98540781]]

  [[0.74300285]
   [0.06124855]]]]
[[[[0.2501103  0.80609755 0.32868076]
   [0.87468871 0.27541785 0.9289837 ]
   [0.94307772 0.92782878 0.36063559]
   [0.53762147 0.60430607 0.74300285]]]


 [[[0.58815102 0.98049858 0.63130771]
   [0.48053308 0.27814212 0.86343307]
   [0.07572209 0.56406903 0.59012648]
   [0.92797601 0

In [10]:
A, B, C, D = 1, 2, 3, 4
x = Pedro_Variable(np.random.rand(A, B, C, D))
y = F.transpose(x, (1, 0, 3, 2))
y.backward(retain_grad=True)

print(x)
print('=' * 50)
print(y)
print('=' * 50)
print(y.grad)
print('=' * 50)
print(x.grad)

NameError: name 'Pedro_Variable' is not defined